<?php

namespace App\Content;

use Illuminate\Support\Collection;

/**
 * Builds the Index from the Documents on disk.
 *
 * Always a full rebuild, never an update: the Index is derived, so the cheapest
 * way to guarantee it agrees with the Documents is to throw it away and make it
 * again. Rendering every Document here is deliberate — it captures the headings
 * search needs, and it is the moment a Document that no longer parses announces
 * itself, rather than at 3am on a reader's page load.
 */
class IndexBuilder
{
    public function __construct(
        private readonly DocumentReader $reader,
        private readonly MarkdownRenderer $renderer,
        private readonly TableOfContents $toc,
    ) {}

    /**
     * @return array{documents: Collection<int, Document>, headings: array<string, array<int, array{text: string, url: string}>>, failures: array<string, array<int, string>>}
     */
    public function build(): array
    {
        [$documents, $failures] = $this->reader->readAll();

        $headings = [];

        foreach ($documents as $document) {
            $headings[$document->slug] = $this->headingsOf($document);
        }

        return ['documents' => $documents, 'headings' => $headings, 'failures' => $failures];
    }

    /**
     * @param  Collection<int, Document>  $documents
     * @param  array<string, array<int, array{text: string, url: string}>>  $headings
     */
    public function write(Collection $documents, array $headings): string
    {
        $path = DocumentIndex::manifestPath();

        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        $manifest = [
            'documents' => $documents->map(fn (Document $d) => $d->toArray())->values()->all(),
            'headings' => $headings,
        ];

        file_put_contents(
            $path,
            "<?php\n\n// Generated by `php artisan blog:build`. Do not edit, do not commit.\n\nreturn ".var_export($manifest, true).";\n"
        );

        return $path;
    }

    /**
     * Every h2 and h3 in a Document, flattened, each with the anchor that
     * scrolls to it.
     *
     * @return array<int, array{text: string, url: string}>
     */
    private function headingsOf(Document $document): array
    {
        $outline = $this->toc->from($this->renderer->renderFresh($document));
        $flattened = [];

        foreach ($outline as $heading) {
            $flattened[] = ['text' => $heading['title'], 'url' => $document->url().'#'.$heading['id']];

            foreach ($heading['children'] as $child) {
                $flattened[] = ['text' => $child['title'], 'url' => $document->url().'#'.$child['id']];
            }
        }

        return $flattened;
    }
}
