name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, mysql
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify your Node.js version
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-progress --no-scripts
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Assets
        run: npm run build  # Command to build your assets
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database
        run: |
          mysql -uroot -ppassword -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS laravel;'
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: user
          DB_PASSWORD: password
        run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Trigger deployment
        env:
          FORGE_SERVER_ID: ${{ secrets.FORGE_SERVER_ID }}
          FORGE_SITE_ID: ${{ secrets.FORGE_SITE_ID }}
          FORGE_DEPLOYMENT_TOKEN: ${{ secrets.FORGE_DEPLOYMENT_TOKEN }}
        run: curl -sS https://forge.laravel.com/servers/${{ env.FORGE_SERVER_ID }}/sites/${{ env.FORGE_SITE_ID }}/deploy/http?token=${{ env.FORGE_DEPLOYMENT_TOKEN }}
